name : "dbt_alternance"
version : "1.0.0"
config-version: 2
profile : "default"

models:
  dbt_alternance : 
    staging :
      +materialized: view
    intermediate :
      +materialized: view
    mart :
      +materialized: table
      rupture :
        +schema : rupture
